sudo: false
language: csharp
solution: FFmpeg.AutoGen.sln
install:
  - nuget restore FFmpeg.AutoGen.sln
script:
  - dotnet restore
  - dotnet build .\FFmpeg.AutoGen.Example\FFmpeg.AutoGen.Example.csproj